[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[forms]]
  name = "basic-package"
  path = "/"

[[forms]]
  name = "custom-package"
  path = "/"

[[forms]]
  name = "high-ticket-package"
  path = "/"
