[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[forms]]
  name = "basic-package"
  path = "/forms/basic"

[[forms]]
  name = "custom-package"
  path = "/forms/custom"

[[forms]]
  name = "high-ticket-package"
  path = "/forms/high-ticket"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
